name = "Meteor-Fatpack"
author = "mrkeww"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3808dfd628822f39a221e5b67aaa7783d937033dcf1d59e1a847f13ed5004042"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"
