name = "Meteor-Fatpack"
author = "mrkeww"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc9408348b5b84b4256de502d2cac6daed558be050143abc478903c324adb666"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"
