name = "Meteor-Fatpack"
author = "mrkeww"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11a21995fcc631ba75d28aaa77f1da3398ecfe82b593603f996842be029d2767"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"
